Add .zip extraction to yabridge repackage script
Since this is always another seemingly unnecessary step in the process.

diff --git a/bin/repackage-yabridge b/bin/repackage-yabridge
--- a/bin/repackage-yabridge
+++ b/bin/repackage-yabridge
@@ -3,6 +3,10 @@
 # For convenience we'll repack the `yabridge-<version>-{,-ubuntu-18.04}.tar.gz`
 # and `yabridgectl-<version>.tar.gz` files generated by the CI into two
 # archives. This script automates that for a file with the given input prefix.
+#
+# This also handles unzipping the zipped tarballs.
+
+set -euo pipefail
 
 prefix=$1
 
@@ -10,20 +14,25 @@ input_yabridge="$prefix.tar.gz"
 input_yabridge_bionic="$prefix-ubuntu-18.04.tar.gz"
 input_yabridgectl="${input_yabridge/yabridge/yabridgectl}"
 
-if [[ ! -f $input_yabridge ]]; then
-  echo "Missing '$input_yabridge'"
-  exit 1
-fi
+input_yabridge_zip="$input_yabridge.zip"
+input_yabridge_bionic_zip="$input_yabridge_bionic.zip"
+input_yabridgectl_zip="$input_yabridgectl.zip"
 
-if [[ ! -f $input_yabridge_bionic ]]; then
-  echo "Missing '$input_yabridge_bionic'"
-  exit 1
-fi
+# If one of these files doesn't exist but there is a zipped version of the same
+# file, then we'll try to unzip it first. GitHub Actions demands you zip your
+# tarballs, because Microsoft.
+for zipped_archive in $input_yabridge_zip $input_yabridge_bionic_zip $input_yabridgectl_zip; do
+  if [[ -f $zipped_archive ]]; then
+    unzip "$zipped_archive" && rm "$zipped_archive"
+  fi
+done
 
-if [[ ! -f $input_yabridgectl ]]; then
-  echo "Missing '$input_yabridgectl'"
-  exit 1
-fi
+for archive in $input_yabridge $input_yabridge_bionic $input_yabridgectl; do
+  if [[ ! -f $archive ]]; then
+    echo "Missing '$archive'"
+    exit 1
+  fi
+done
 
 working_dir=$(mktemp -d)
 
